version: '3'

services:
  drone-management-api:
    environment:
      DEFAULT_SETTINGS: POSTGRESQL
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8181:80

  drone-management-migrator:
    environment:
      DEFAULT_SETTINGS: POSTGRESQL
      WAIT_BEFORE_CLOSE: "FALSE"

  drone-management-adhoc-console:
    image: ${REPO}drone.management.adhoc.console
    build:
      context: .
      dockerfile: Drone.Management.AdHoc/Drone.Management.AdHoc.Console/Dockerfile
    environment:
      DEFAULT_SETTINGS: POSTGRESQL
      SETTINGS: ${SETTINGS}
      API_BASE_ADDRESS: http://drone-management-api:80/
      N_TEST_DATAS: "5"
      WAIT_BEFORE_CLOSE: "FALSE"
      MS_START_DELAY: "3000"
      MIGRATE_TEST_DATA: "TRUE"
      VERIFY_MIGRATED_TEST_DATA: "TRUE"
      DELETE_MIGRATED_TEST_DATA: "FALSE"
    depends_on:
      - drone-management-api
    networks:
      - drone-management-network