version: '3'

services:

# ERROR: Full solution test is not working properly with current dotnet image build.
#  drone.management.tests:
#    image: ${AUTHOR}dronemanagementtests
#    build:
#      context: .
#      dockerfile: Drone.Management.Tests/Dockerfile

  drone.management.adhoc.tests:
    image: ${AUTHOR}dronemanagementadhoctests
    build:
      context: .
      dockerfile: Drone.Management.Tests/Drone.Management.AdHoc.Tests/Dockerfile

  drone.management.settings.tests:
    image: ${AUTHOR}dronemanagementsettingstests
    build:
      context: .
      dockerfile: Drone.Management.Tests/Drone.Management.Settings.Tests/Dockerfile

  drone.management.repository.tests:
    image: ${AUTHOR}dronemanagementrepositorytests
    build:
      context: .
      dockerfile: Drone.Management.Tests/Drone.Management.Repository.Tests/Dockerfile

  drone.management.migrator.tests:
    image: ${AUTHOR}dronemanagementmigratortests
    build:
      context: .
      dockerfile: Drone.Management.Tests/Drone.Management.Migrator.Tests/Dockerfile

  drone.management.config.tests:
    image: ${AUTHOR}dronemanagementconfigtests
    build:
      context: .
      dockerfile: Drone.Management.Tests/Drone.Management.Config.Tests/Dockerfile

  drone.management.api.tests:
    image: ${AUTHOR}dronemanagementapitests
    build:
      context: .
      dockerfile: Drone.Management.Tests/Drone.Management.API.Tests/Dockerfile

  drone.management.business.tests:
    image: ${AUTHOR}dronemanagementbusinesstests
    build:
      context: .
      dockerfile: Drone.Management.Tests/Drone.Management.Business.Tests/Dockerfile
